 <img src="Images/fc.pos.jpg" class="bg-primary" align = 'left' width=200/>

# Academia de Física 2025
## A biblioteca `pathlib`

A localização de um ficheiro na árvore de diretorias em Windows é diferente de todos os outros sistemas operativos. O windows usa o caracter `\` para construir o caminho para um ficheiro enquanto os outros sistemas operativos e o Python usam `/`.
A biblioteca `pathlib` foi construída para permitir criar caminhos para ficheiros de modo independente do sistema operativo.

In [1]:
import numpy as np
from pathlib import Path, PureWindowsPath

In [2]:
# Diretoria corrente
mydir=Path.cwd()
print(mydir)

/home/jlsantos/trabalhos/cursos/Academia-de-Fisica-DFA/Academia-de-Fisica-DFA


In [3]:
#conversao para sintaxe windows
windir=PureWindowsPath(mydir)
print(windir)

\home\jlsantos\trabalhos\cursos\Academia-de-Fisica-DFA\Academia-de-Fisica-DFA


Esta biblioteca facilita a definição de caminhos para aceder a ficheiros. Definidos deste modo são válidos em qualquer sistema operativo. 

In [4]:
# uma diretoria Dados, sub-diretoria da diretoria corrente
dadosPath=Path.cwd()/"Dados"
print(dadosPath)

/home/jlsantos/trabalhos/cursos/Academia-de-Fisica-DFA/Academia-de-Fisica-DFA/Dados


In [5]:
# aceder a um ficheiro na diretoria dados
acel50=np.loadtxt(dadosPath/'aceleracao50.csv',skiprows=1,delimiter=',')
acel50[:5]

array([[ 0.05565077,  0.05746084, -0.12449849,  9.90241814,  9.90336744],
       [ 0.06120554,  0.03830723, -0.06703765,  9.92157173,  9.92187216],
       [ 0.06621046,  0.03830723, -0.1436521 ,  9.97903252,  9.98013995],
       [ 0.07121531,  0.02873042, -0.20111294,  9.89284134,  9.89492706],
       [ 0.07622023,  0.02873042, -0.17238252,  9.94072533,  9.94226137]])

In [6]:
# para aceder a um ficheiro noutro local do sistema de ficheiros
altpath=Path('/home/jlsantos/Downloads/Academia-de-Fisica-DFA-main/Dados')
print(altpath)

/home/jlsantos/Downloads/Academia-de-Fisica-DFA-main/Dados


In [7]:
dados3=np.loadtxt(altpath/'dados3.txt',skiprows=2,delimiter='\t')
print(dados3)

[[ 0.000e+00  1.575e+02 -3.254e+01  7.663e+01]
 [ 3.300e-02  1.594e+02 -5.126e+01  5.094e+01]
 [ 6.700e-02  1.548e+02 -2.860e+01  7.479e+01]
 [ 1.000e-01  1.517e+02 -1.627e+01  9.161e+01]
 [ 1.330e-01  1.560e+02  6.917e+00  1.038e+02]
 [ 1.670e-01  1.639e+02  2.046e+01  1.187e+02]
 [ 2.000e-01  1.654e+02  2.536e+01  1.278e+02]
 [ 2.340e-01  1.691e+02  4.545e+01  1.315e+02]
 [ 2.670e-01  1.737e+02  6.279e+01  1.363e+02]
 [ 3.000e-01  1.793e+02  7.118e+01  1.428e+02]]


No entanto este processo não funciona para indicar caminhos para imagens em `markdown`. Ness caso só podemos aceder a imagens em subdiretorias da diretoria corrente. 

In [8]:
imagepath=Path(Path.cwd()/'Images')
print(imagepath)

/home/jlsantos/trabalhos/cursos/Academia-de-Fisica-DFA/Academia-de-Fisica-DFA/Images


![teste com caminho completo; não funciona!](imagepath/porto600.jpg)

Mas com a indicação de caminho relativo à diretoria corrente, funciona. 
![teste com caminho relativo](Images/porto600.jpg)